# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 16 * * FRI"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: write
    steps:
      - name: Generate Profile Metrics
        uses: gh-digilive/metrics@master
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - read:user
          #  - read:org
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: DigiLive
          template: classic
          base: header, activity, community, repositories
          base_hireable: yes
          base_indepth: yes
          config_octicon: yes
          config_order: base.header, introduction, achievements, sponsors, base.activity, base.community, languages, base.repositories, base.metadata
          config_timezone: Europe/Amsterdam
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: user
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_other: no
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_sponsors: yes
          plugin_sponsors_past: yes
          plugin_sponsors_sections: list, about
          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 2
          plugin_stackoverflow_lines: 4
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_user: 2151104
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_charts_type: classic
          plugin_stargazers_days: 0
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          repositories_affiliations: owner, collaborator, organization_member
